version: "3"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: >
      sh -c "cd Dictionary-Server && cargo test"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=somepassword
    depends_on:
      - db

  db:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=somepassword
    